// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hamt from "./impl/Hamt.js";

function make(hasher) {
  return {
          root: Hamt.empty(undefined),
          count: 0,
          hasher: hasher
        };
}

function get(param, k) {
  return Hamt.find(param.root, 0, param.hasher(k), k);
}

function set(m, k, v) {
  var hasher = m.hasher;
  var root$p = Hamt.assoc(m.root, 0, hasher, hasher(k), k, v);
  if (root$p !== undefined) {
    return {
            root: root$p,
            count: m.count + 1 | 0,
            hasher: m.hasher
          };
  } else {
    return m;
  }
}

function remove(m, k) {
  var root$p = Hamt.dissoc(m.root, 0, m.hasher(k), k);
  if (root$p !== undefined) {
    return {
            root: root$p,
            count: m.count - 1 | 0,
            hasher: m.hasher
          };
  } else {
    return m;
  }
}

function size(m) {
  return m.count;
}

export {
  make ,
  get ,
  set ,
  remove ,
  size ,
  
}
/* No side effect */
