// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hash from "./impl/Hash.js";
import * as HashMap from "./HashMap.js";

var empty = {
  hashMap: HashMap.make(Hash.hashInt)
};

function get(s, v) {
  var match = HashMap.get(s.hashMap, v);
  if (match !== undefined) {
    return v;
  }
  
}

function set(s, v) {
  return {
          hashMap: HashMap.set(s.hashMap, v, undefined)
        };
}

function remove(s, v) {
  return {
          hashMap: HashMap.remove(s.hashMap, v)
        };
}

function size(s) {
  return HashMap.size(s.hashMap);
}

function fromArray(ar) {
  var s = {
    contents: empty
  };
  ar.forEach(function (x) {
        s.contents = set(s.contents, x);
        
      });
  return s.contents;
}

export {
  empty ,
  get ,
  set ,
  remove ,
  size ,
  fromArray ,
  
}
/* empty Not a pure module */
