// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hamt from "./impl/Hamt.mjs";

function make(hasher) {
  return {
          root: Hamt.BitmapIndexed.make(0, []),
          count: 0,
          hasher: hasher
        };
}

function get(param, k) {
  return Hamt.BitmapIndexed.find(param.root, 0, param.hasher(k), k);
}

function set(m, k, v) {
  var hasher = m.hasher;
  var root = m.root;
  var root$p = Hamt.BitmapIndexed.assoc(root, 0, hasher, hasher(k), k, v);
  if (root$p === root) {
    return m;
  } else {
    return {
            root: root$p,
            count: m.count + 1 | 0,
            hasher: m.hasher
          };
  }
}

function remove(m, k) {
  var hasher = m.hasher;
  var root = m.root;
  var root$p = Hamt.BitmapIndexed.dissoc(root, 0, hasher(k), k);
  if (root$p !== undefined) {
    if (root$p === root) {
      return m;
    } else {
      return {
              root: root$p,
              count: m.count - 1 | 0,
              hasher: m.hasher
            };
    }
  } else {
    return make(hasher);
  }
}

function size(m) {
  return m.count;
}

export {
  make ,
  get ,
  set ,
  remove ,
  size ,
  
}
/* No side effect */
