// Generated by ReScript, PLEASE EDIT WITH CARE


function hash(k) {
  switch (k) {
    case "Sir Bedevere" :
        return 250;
    case "Sir Lancelot" :
        return 146;
    case "Sir Robin" :
        return 13;
    default:
      return 0;
  }
}

export {
  hash ,
  
}
/* No side effect */
