// Generated by ReScript, PLEASE EDIT WITH CARE


function hashInt(n) {
  return (n >>> 1) & 1073741824 | n & -1073741825;
}

let stringHashCache = {}
let stringHashCacheCount = 0;

function stringHash(s) {
  let h = 0;
  for (let i = 0, len = s.length; i < len; ++i){
    h = Math.imul(31, h) + s.charCodeAt(i);
  }
  return hashInt(h);
}
;

var hashString = (function (s) {
  let h = stringHashCache[s];
  if (h !== undefined) {
    return h;
  }

  if (stringHashCacheCount > 255) {
    stringHashCache = {};
    stringHashCacheCount = 0;
  }
  
  h = stringHash(s);
  stringHashCache[s] = h;
  stringHashCacheCount++;

  return h;
});

export {
  hashInt ,
  hashString ,
  
}
/*  Not a pure module */
