// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vector from "../src/Vector.mjs";
import * as Caml_obj from "@rescript/std/lib/es6/caml_obj.js";
import * as Belt_Array from "@rescript/std/lib/es6/belt_Array.js";

var v0 = Vector.fromArray(Belt_Array.makeBy(100, (function (i) {
            return Math.imul(i, i);
          })));

var v = Vector.makeByU(100, (function (i) {
        return Math.imul(i, i);
      }));

Vector.forEachWithIndex(v, (function (i, ii) {
        console.log(i, ii);
        
      }));

if (!Caml_obj.caml_equal(v, v0)) {
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "scratch.res",
          13,
          0
        ],
        Error: new Error()
      };
}

var A;

var V;

export {
  A ,
  V ,
  v0 ,
  v ,
  
}
/* v0 Not a pure module */
