// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_List from "@rescript/std/lib/es6/belt_List.js";

var empty = [
  /* [] */0,
  /* [] */0
];

function make(param) {
  return empty;
}

function isEmpty(param) {
  return Belt_List.size(param[0]) === 0;
}

function checkf(fr) {
  if (fr[0]) {
    return fr;
  } else {
    return [
            Belt_List.reverse(fr[1]),
            /* [] */0
          ];
  }
}

function snoc(param, x) {
  return checkf([
              param[0],
              {
                hd: x,
                tl: param[1]
              }
            ]);
}

function head(q) {
  var match = q[0];
  if (match) {
    return match.hd;
  }
  throw {
        RE_EXN_ID: "Not_found",
        Error: new Error()
      };
}

function tail(q) {
  var match = q[0];
  if (match) {
    return checkf([
                match.tl,
                q[1]
              ]);
  }
  throw {
        RE_EXN_ID: "Not_found",
        Error: new Error()
      };
}

export {
  empty ,
  make ,
  isEmpty ,
  snoc ,
  head ,
  tail ,
}
/* No side effect */
