// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hamt from "./impl/Hamt.mjs";
import * as Hash from "./impl/Hash.mjs";

function make(param) {
  return {
          root: Hamt.make(undefined)
        };
}

function get(param, k) {
  return Hamt.find(param.root, 0, Hash.hash(k), k);
}

function set(param, k, v) {
  return {
          root: Hamt.assoc(param.root, 0, Hash.hash(k), k, v)
        };
}

function remove(param, k) {
  var root$p = Hamt.dissoc(param.root, 0, Hash.hash(k), k);
  if (root$p !== undefined) {
    return {
            root: root$p
          };
  } else {
    return {
            root: Hamt.make(undefined)
          };
  }
}

export {
  make ,
  get ,
  set ,
  remove ,
  
}
/* Hamt Not a pure module */
