// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hamt from "./impl/Hamt.mjs";
import * as Hash from "./impl/Hash.mjs";

function make(param) {
  return {
          root: Hamt.make(undefined),
          count: 0
        };
}

function get(param, k) {
  return Hamt.find(param.root, 0, Hash.hash(k), k);
}

function set(m, k, v) {
  var root = m.root;
  var root$p = Hamt.assoc(root, 0, Hash.hash(k), k, v);
  if (root$p === root) {
    return m;
  } else {
    return {
            root: root$p,
            count: m.count - 1 | 0
          };
  }
}

function remove(m, k) {
  var root = m.root;
  var root$p = Hamt.dissoc(root, 0, Hash.hash(k), k);
  if (root$p !== undefined) {
    if (root$p === root) {
      return m;
    } else {
      return {
              root: root$p,
              count: m.count - 1 | 0
            };
    }
  } else {
    return {
            root: Hamt.make(undefined),
            count: 0
          };
  }
}

function size(m) {
  return m.count;
}

export {
  make ,
  get ,
  set ,
  remove ,
  size ,
  
}
/* Hamt Not a pure module */
