// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Map from "./Map.mjs";
import * as Caml_option from "@rescript/std/lib/es6/caml_option.js";

function make(hasher) {
  return {
          hashMap: $$Map.make(hasher)
        };
}

function get(s, v) {
  var match = $$Map.get(s.hashMap, v);
  if (match !== undefined) {
    return Caml_option.some(v);
  }
  
}

function set(s, v) {
  return {
          hashMap: $$Map.set(s.hashMap, v, undefined)
        };
}

function remove(s, v) {
  return {
          hashMap: $$Map.remove(s.hashMap, v)
        };
}

function size(s) {
  return $$Map.size(s.hashMap);
}

export {
  make ,
  get ,
  set ,
  remove ,
  size ,
  
}
/* No side effect */
