// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Map from "./Map.mjs";

function make(param) {
  return {
          hashMap: $$Map.make(undefined)
        };
}

function get(s, v) {
  var match = $$Map.get(s.hashMap, v);
  if (match !== undefined) {
    return v;
  }
  
}

function set(s, v) {
  return {
          hashMap: $$Map.set(s.hashMap, v, undefined)
        };
}

function remove(s, v) {
  return {
          hashMap: $$Map.remove(s.hashMap, v)
        };
}

function size(s) {
  return $$Map.size(s.hashMap);
}

export {
  make ,
  get ,
  set ,
  remove ,
  size ,
  
}
/* Map Not a pure module */
