// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Garter_Obj = require("./Garter_Obj");

function fromKV(prim, prim$1) {
  return Garter_Obj.fromKV(prim, prim$1);
}

exports.fromKV = fromKV;
/* ./Garter_Obj Not a pure module */
