// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");

function isEmpty(xs) {
  return xs.length === 0;
}

function lastUnsafe(ar) {
  return ar[ar.length - 1 | 0];
}

function last(ar) {
  if (ar.length === 0) {
    return ;
  } else {
    return Caml_option.some(lastUnsafe(ar));
  }
}

exports.isEmpty = isEmpty;
exports.last = last;
exports.lastUnsafe = lastUnsafe;
/* No side effect */
