// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function toArray(s) {
  return Array.from(s);
}

function charCode(s) {
  return s.charCodeAt(0) | 0;
}

exports.toArray = toArray;
exports.charCode = charCode;
/* No side effect */
