// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Id = require("bs-platform/lib/js/belt_Id.js");

function cmp(a, b) {
  return a.localeCompare(b) | 0;
}

var StringComparable = Belt_Id.MakeComparableU({
      cmp: cmp
    });

function cmp$1(a, b) {
  return a - b | 0;
}

var IntComparable = Belt_Id.MakeComparableU({
      cmp: cmp$1
    });

exports.StringComparable = StringComparable;
exports.IntComparable = IntComparable;
/* StringComparable Not a pure module */
