// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Id = require("bs-platform/lib/js/belt_Id.js");

function cmp(a, b) {
  return a.localeCompare(b) | 0;
}

var StringComparable = Belt_Id.MakeComparableU({
      cmp: cmp
    });

exports.StringComparable = StringComparable;
/* StringComparable Not a pure module */
