// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function takeExn(list, cnt) {
  var l = Belt_List.take(list, cnt);
  if (l !== undefined) {
    return l;
  }
  throw {
        RE_EXN_ID: "Not_found",
        Error: new Error()
      };
}

function dropExn(list, cnt) {
  var l = Belt_List.drop(list, cnt);
  if (l !== undefined) {
    return l;
  }
  throw {
        RE_EXN_ID: "Not_found",
        Error: new Error()
      };
}

function orderedPairs(xs) {
  if (!xs) {
    return /* [] */0;
  }
  var ys = xs.tl;
  var x = xs.hd;
  return Pervasives.$at(Belt_List.map(ys, (function (y) {
                    return [
                            x,
                            y
                          ];
                  })), orderedPairs(ys));
}

exports.takeExn = takeExn;
exports.dropExn = dropExn;
exports.orderedPairs = orderedPairs;
/* No side effect */
