// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function toArray(s) {
  return Array.from(s);
}

function charCode(s) {
  return s.charCodeAt(0) | 0;
}

var $$String = {
  toArray: toArray,
  charCode: charCode
};

function first(param) {
  return param[0];
}

function second(param) {
  return param[1];
}

var Pair = {
  first: first,
  second: second
};

var $$Array;

var Id;

var Int;

var List;

var Obj;

var Vector;

exports.$$Array = $$Array;
exports.Id = Id;
exports.Int = Int;
exports.List = List;
exports.Obj = Obj;
exports.Vector = Vector;
exports.$$String = $$String;
exports.Pair = Pair;
/* No side effect */
